using IfcToolkit;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public class CreateFBX : MonoBehaviour
{
    public GameObject ifcFilePanel;

    public GameObject ifcButton;
    public Transform buttonParent;

    private List<Button> btns = new List<Button>();

    public void CreateAsset(string fileName)
    {
        GameObject go = Resources.Load<GameObject>(fileName);
        Instantiate(go);
    }

    public void PanelActive()
    {
        bool isActive = false;

        isActive = ifcFilePanel.activeSelf ? false : true;

        if (isActive)
        {
            GameObject go = Instantiate(ifcButton, buttonParent);
            Button btn = go.GetComponent<Button>();
            btn.onClick.AddListener(AddButtonMethod);
            btns.Add(btn);

            CreateIFC("Assets/Resources/" + "IFCTest.ifc");
        }
        else
        {
            for(int i = 0; i < btns.Count; i++)
            {
                Destroy(btns[i].gameObject);
            }

            btns.Clear();
        }

        ifcFilePanel.SetActive(isActive);
    }

    private void AddButtonMethod()
    {
        CreateAsset("IFCTest");
    }

    private static List<string> assetPaths = new List<string>();
    private static DateTime? assetCreateTime = null;

    private void CreateIFC(string path)
    {
        if (path.EndsWith(".ifc"))
        {
            //UnityEngine.Debug.Log("Preprocessing " + assetPath);
            bool editor = true;
            IfcImporter.ProcessIfc(path, IfcSettingsWindow.options, editor);

            //Import the newly created files
            //string outputFile = "Assets/Resources/" + System.IO.Path.GetFileNameWithoutExtension(path); //확장자명을 제거한 뒤 경로 지정
            //AssetDatabase.ImportAsset(outputFile + "_dae.dae", ImportAssetOptions.ForceUpdate);
            //AssetDatabase.ImportAsset(outputFile + "_xml.xml", ImportAssetOptions.ForceUpdate);

            //assetPaths.Add(path);

            //if (assetCreateTime is null)
            //{
            //    //Keep trying to finish the job until we can load the dae file
            //    EditorApplication.update += AttemptFinishImport;

            //    AttemptFinishImport();
            //}
            ////Keep track of the time so we don't get stuck trying to import something forever
            //assetCreateTime = System.DateTime.Now;
        }
    }

    ///<summary>Creates prefabs for newly detected .ifc files.</summary>
    ///<remarks>Will keep retrying until the dae file exists.</remarks>
    private void AttemptFinishImport()
    {
        foreach (string assetPath in new List<string>(assetPaths))
        {
            string resourceName = System.IO.Path.GetFileNameWithoutExtension(assetPath);

            if (Resources.Load(resourceName + "_dae") != null)
            {
                assetPaths.Remove(assetPath);

                GameObject gameObject = IfcImporter.LoadDae(assetPath);

                string xml_path = "Assets/Resources/" + resourceName + "_xml.xml";
                IfcXmlParser.parseXmlFile(xml_path, gameObject, IfcSettingsWindow.options);

                //Store filename in Ifc File component
                IfcFile ifcFile = gameObject.AddComponent<IfcFile>() as IfcFile;
                ifcFile.ifcFileName = resourceName;
                ifcFile.ifcFilePath = assetPath;
                ifcFile.geometryFileFormat = "DAE";

                //Move the model to origin if keepOriginalPositionEnabled is false
                if (!IfcSettingsWindow.options.keepOriginalPositionEnabled)
                {
                    IfcImporter.MoveToOrigin(gameObject);
                }
                if (!IfcSettingsWindow.options.keepOriginalPositionForPartsEnabled)
                {
                    IfcImporter.MovePartsToOrigin(gameObject);
                }

                PrefabSaver.savePrefab(gameObject, assetPath);

                if (assetPaths.Count == 0)
                {
                    EditorApplication.update -= AttemptFinishImport;
                    assetCreateTime = null;
                    return;
                }
            }
        }

        //Abort if more than ten seconds have passed since the dae should've been created
        if (assetCreateTime == null || System.DateTime.Now - assetCreateTime > new TimeSpan(0, 0, 10))
        {
            Debug.Log("Loading the .dae file generated by IfcConvert failed.");
            EditorApplication.update -= AttemptFinishImport;
            assetCreateTime = null;
            assetPaths = new List<string>();
        }
    }
}
